import { createElement, Activity, ArrowLeft, ArrowUpRight, Bell, BellRing, BookOpen, Box, Boxes, Braces, Bug, Calendar, ChartLine, ChartNoAxesColumn, Check, ChevronDown, CircleCheck, CircleHelp, CirclePlus, Clipboard, Code, Download, ExternalLink, FolderOpen, FolderPlus, GitBranch, Github, Globe, Grid2X2, Grid3X3, GripVertical, History, House, Inbox, Info, KeyRound, Layers, LayoutGrid, ListChecks, ListFilter, LogIn, LogOut, Mail, Megaphone, Menu, MessageSquare, MessagesSquare, Network, OctagonAlert, PanelTop, Pencil, Plus, Radar, RefreshCw, Save, Search, Send, Server, Settings, ShieldCheck, SlidersHorizontal, Smile, SquarePen, SunMoon, Table, Tag, Terminal, Trash2, TriangleAlert, Upload, UserPlus, Users, X, Zap } from 'lucide';
const icons = {'activity':Activity,'arrow-left':ArrowLeft,'arrow-up-right':ArrowUpRight,'bell':Bell,'bell-ring':BellRing,'book-open':BookOpen,'box':Box,'boxes':Boxes,'braces':Braces,'bug':Bug,'calendar':Calendar,'chart-line':ChartLine,'chart-no-axes-column':ChartNoAxesColumn,'check':Check,'chevron-down':ChevronDown,'circle-check':CircleCheck,'circle-help':CircleHelp,'circle-plus':CirclePlus,'clipboard':Clipboard,'code':Code,'download':Download,'external-link':ExternalLink,'folder-open':FolderOpen,'folder-plus':FolderPlus,'git-branch':GitBranch,'github':Github,'globe':Globe,'grid-2x2':Grid2X2,'grid-3x3':Grid3X3,'grip-vertical':GripVertical,'history':History,'house':House,'inbox':Inbox,'info':Info,'key-round':KeyRound,'layers':Layers,'layout-grid':LayoutGrid,'list-checks':ListChecks,'list-filter':ListFilter,'log-in':LogIn,'log-out':LogOut,'mail':Mail,'megaphone':Megaphone,'menu':Menu,'message-square':MessageSquare,'messages-square':MessagesSquare,'network':Network,'octagon-alert':OctagonAlert,'panel-top':PanelTop,'pencil':Pencil,'plus':Plus,'radar':Radar,'refresh-cw':RefreshCw,'save':Save,'search':Search,'send':Send,'server':Server,'settings':Settings,'shield-check':ShieldCheck,'sliders-horizontal':SlidersHorizontal,'smile':Smile,'square-pen':SquarePen,'sun-moon':SunMoon,'table':Table,'tag':Tag,'terminal':Terminal,'trash-2':Trash2,'triangle-alert':TriangleAlert,'upload':Upload,'user-plus':UserPlus,'users':Users,'x':X,'zap':Zap };
export function renderIcons() {
  document.querySelectorAll('[data-icon]').forEach(host => {
    if (host.dataset.renderedIcon === host.dataset.icon) return;
    const definition = icons[host.dataset.icon];
    if (!definition) return;
    host.replaceChildren(createElement(definition, { width: 18, height: 18, 'stroke-width': 1.7, 'aria-hidden': 'true' }));
    host.dataset.renderedIcon = host.dataset.icon;
  });
}
