package tech.wenisch.kairos.config;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.UUID;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;

class FlywayMigrationConfigTest {

    @Test
    void registeredJavaMigrationsApplyRepairAfterVersion31Baseline() throws Exception {
        String url = "jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        try (Connection connection = DriverManager.getConnection(url)) {
            connection.createStatement().executeUpdate(
                    "CREATE TABLE resource_type_config ("
                            + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                            + "type_name VARCHAR(255))");
            connection.createStatement().executeUpdate(
                    "INSERT INTO resource_type_config (type_name) VALUES ('HTTP')");
        }

        var configuration = Flyway.configure()
                .dataSource(url, null, null)
                .baselineOnMigrate(true)
                .baselineVersion("31");
        new FlywayMigrationConfig().kairosFlywayJavaMigrations().customize(configuration);

        configuration.load().migrate();

        try (Connection connection = DriverManager.getConnection(url);
             ResultSet rs = connection.createStatement().executeQuery(
                     "SELECT availability_percentage_decimal_places FROM resource_type_config WHERE type_name = 'HTTP'")) {
            assertThat(rs.next()).isTrue();
            assertThat(rs.getInt(1)).isEqualTo(2);
        }
    }
}