CREATE TABLE IF NOT EXISTS api_key (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE api_key_permission (
    api_key_id BIGINT NOT NULL,
    permission VARCHAR(64) NOT NULL,
    PRIMARY KEY (api_key_id, permission),
    CONSTRAINT fk_api_key_permission_api_key
        FOREIGN KEY (api_key_id) REFERENCES api_key (id) ON DELETE CASCADE
);

INSERT INTO api_key_permission (api_key_id, permission)
SELECT id, 'STATUS_READ' FROM api_key;

INSERT INTO api_key_permission (api_key_id, permission)
SELECT id, 'CHECK_EXECUTE' FROM api_key;

INSERT INTO api_key_permission (api_key_id, permission)
SELECT id, 'RESOURCE_MANAGE' FROM api_key;

INSERT INTO api_key_permission (api_key_id, permission)
SELECT id, 'ANNOUNCEMENT_MANAGE' FROM api_key;

INSERT INTO api_key_permission (api_key_id, permission)
SELECT id, 'MCP_ACCESS' FROM api_key;
